name: Deploy to Firebase Hosting

on:
  push:
    branches: [release/beta]

jobs:
  deploy_to_firebase:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Generate package-lock.json
        run: npm i --package-lock-only
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: NODE_ENV=production REACT_APP_PROXY_URL=${{ secrets.PROXY_URL }} npm run build
      - name: Deploy to firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_COURIER_007 }}'
          channelId: live
          projectId: courier-007
