name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
      - name: Deploy to firebase Hosting
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_COURIER_007 }}"
          channelId: live
          projectId: courier-007
